### ISSUE TITLE
老哥你好

### ISSUE THREAD

**Issue by iceriverdog** [wangjc0216/updateconfig#1]
我的操作步骤如下：

1.启动byfn
2.clone下你的项目，修改路径
3.go test -v main_test.go

然后就报错了，错误如下，是不是我步骤有问题。谢谢！
=== RUN   TestADDORG
 [fabsdk/fab] 2020/08/17 05:21:20 UTC - fab.detectDeprecatedNetworkConfig -> WARN Getting orderers from endpoint config channels.orderer is deprecated, use entity matchers to override orderer configuration
 [fabsdk/fab] 2020/08/17 05:21:20 UTC - fab.detectDeprecatedNetworkConfig -> WARN visit https://github.com/hyperledger/fabric-sdk-go/blob/master/test/fixtures/config/overrides/local_entity_matchers.yaml for samples
2020/08/17 13:21:20 c.ctx err user not found
    main_test.go:26: user not found
--- FAIL: TestADDORG (0.43s)
FAIL
FAIL    command-line-arguments  0.449s
FAIL

**Comment by wangjc0216** [comment]
bro，可否贴上fabric的错误日志和org1，org2那两个配置文件，我怀疑可能是配置写错了。
自己也可以修改成如下进行尝试
crossG, err := org.NewCfgGroup(crossName, org.WithTxPath(txpath),org.WithUserType("Admin"))；
设置UserType为Admin，默认是小写的admin，我在应用的时候这个地方因为fabric版本不同也会有出错的可能。

**Comment by wangjc0216** [comment]
> 我的操作步骤如下：
> 
> 1.启动byfn
> 2.clone下你的项目，修改路径
> 3.go test -v main_test.go
> 
> 然后就报错了，错误如下，是不是我步骤有问题。谢谢！
> === RUN TestADDORG
> [fabsdk/fab] 2020/08/17 05:21:20 UTC - fab.detectDeprecatedNetworkConfig -> WARN Getting orderers from endpoint config channels.orderer is deprecated, use entity matchers to override orderer configuration
> [fabsdk/fab] 2020/08/17 05:21:20 UTC - fab.detectDeprecatedNetworkConfig -> WARN visit https://github.com/hyperledger/fabric-sdk-go/blob/master/test/fixtures/config/overrides/local_entity_matchers.yaml for samples
> 2020/08/17 13:21:20 c.ctx err user not found
> main_test.go:26: user not found
> --- FAIL: TestADDORG (0.43s)
> FAIL
> FAIL command-line-arguments 0.449s
> FAIL

bro，可否贴上fabric的错误日志和org1，org2那两个配置文件，我怀疑可能是配置写错了。
自己也可以修改成如下进行尝试
crossG, err := org.NewCfgGroup(crossName, org.WithTxPath(txpath),org.WithUserType("Admin"))；
设置UserType为Admin，默认是小写的admin，我在应用的时候这个地方因为fabric版本不同也会有出错的可能。
